apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec: 
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata: 
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: anil13020:java-web-app-jenkins:5
        ports:
        - containerPort: 8080
        reources: 
          requests: 
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata: 
  name: javawebappsvc
spec: 
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: javawebdeploymenthpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: javawebappdeployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: utilization
        averageUtilization: 40
